version: "3"

tasks:
  hm-switch:
    cmds:
      - home-manager switch --flake .

  flake-update:
    cmds:
      - nix flake update

  create-flake-update-branch:
    cmds:
      - git checkout -b feature/update-flakes-$(date +"%d%m%y")

  create-flake-update-pr:
    cmds:
      - gh pr create --title "Flake lock file updates" --body "Regular maintenence updates in order to keep packages up to date." --label "flake-update"

  list-vscode-extension-updates:
    cmds:
      - ./vscode_updater.py

  format:
    cmds:
      - nix fmt

  clean-older-generations:
    cmds:
      - nix-collect-garbage -d

  dnf-install:
    cmds:
      - cmd: sudo dnf install {{ .ITEM }}
        for:
          - wireshark # Troublesome via nix/hm

          # Fixes for SMB drives on the network
          - smbclient
          - samba
          - gvfs-smb
